update logic

diff --git a/bin/git b/bin/git
--- a/bin/git
+++ b/bin/git
@@ -2,27 +2,38 @@
 set -eo pipefail
 
 exit_error() {
-    echo "ERROR: detected running in vscode. Aborting."
-    exit 1
+  echo "ERROR: detected running in vscode. Aborting."
+  exit 1
 }
 
-if [[ -n $VSCODE_INJECTION && $VSCODE_INJECTION == "1" ]]; then
-  ## if in VSCode, unset SSH_AUTH_SOCK to avoid endless 1Password prompt for ssh-agent
-  ## dev container seems to still set it, so we control from ssh wrapper
-  export SSH_AUTH_SOCK=""
-  export GPG_SIGN=""
-  if echo "$@" | grep -q -E '(fetch|pull|push)'; then
-    if /usr/bin/git remote -v | grep -q '@'; then
-      exit_error
+if [[ ! -e "$HOME/.allowed_git_remote" ]]; then
+  if [[ -n $VSCODE_INJECTION && $VSCODE_INJECTION == "1" ]] || [[ -n $VSCODE_GIT_IPC_HANDLE || -n $VSCODE_NONCE ]]; then
+    ## if in VSCode, unset SSH_AUTH_SOCK to avoid endless 1Password prompt for ssh-agent
+    ## dev container seems to still set it, so we control from ssh wrapper
+    export SSH_AUTH_SOCK=""
+    export GPG_SIGN=""
+    if echo "$@" | grep -q -E '(devcontainer-dotfiles)'; then
+      # allow for devcontainer-dotfiles
+      sleep 0
+    else
+      if echo "$@" | grep -q -E '(fetch|pull|push)'; then
+        if /usr/bin/git remote -v | grep -q '@'; then
+          exit_error
+        fi
+      fi
+      if echo "$@" | grep -q 'clone .*@'; then
+        exit_error
+      fi
     fi
   fi
-  if echo "$@" | grep -q 'clone .*@'; then
-    exit_error
-  fi
-else
-  # if not in VSCode, set ssh-agent
-  export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
-  if echo "$@" | grep -q -E "(amend|commit|merge|rebase|revert|$(/usr/bin/git config --get-regexp '^alias\.' | grep -E 'amend|commit|rebase|merge|revert' | sed -e 's/^alias\.//g' -e 's/ .*//g' | tr '\n' '|' | sed 's,|$,,'))"; then
+fi
+
+# if not in VSCode (eg Terminal), set ssh-agent
+export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
+
+# dynamically add gpg-sign if allowed or not vscode
+if [[ -e "$HOME/.allowed_git_sign" ]] || [[ -z $VSCODE_INJECTION || $VSCODE_INJECTION != "1" ]] && [[ -z $VSCODE_GIT_IPC_HANDLE && -z $VSCODE_NONCE ]]; then
+  if echo "$@" | sed -e 's,committer,,ig' -e 's,reverts,,ig' | grep -q -E "(amend|commit|merge|rebase|revert|$(/usr/bin/git config --get-regexp '^alias\.' | grep -E 'amend|commit|rebase|merge|revert' | sed -e 's/^alias\.//g' -e 's/ .*//g' | tr '\n' '|' | sed 's,|$,,'))"; then
     export GPG_SIGN="--gpg-sign"
   fi
 fi
diff --git a/bin/op-ssh-sign b/bin/op-ssh-sign
--- a/bin/op-ssh-sign
+++ b/bin/op-ssh-sign
@@ -2,19 +2,21 @@
 set -eo pipefail
 
 exit_error() {
-    echo "ERROR: detected running in vscode. Aborting."
-    exit 1
+  echo "ERROR: detected running in vscode. Aborting."
+  exit 1
 }
 
-if [[ -n $VSCODE_INJECTION && $VSCODE_INJECTION == "1" ]]; then
-  ## if in VSCode, unset SSH_AUTH_SOCK to avoid endless 1Password prompt for ssh-agent
-  ## dev container seems to still set it, so we control from ssh wrapper
-  export SSH_AUTH_SOCK=""
-  exit_error
-else
-  # if not in VSCode, set ssh-agent
-  export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
+if [[ ! -e "$HOME/.allowed_git_sign" ]]; then
+  if [[ -n $VSCODE_INJECTION && $VSCODE_INJECTION == "1" ]] || [[ -n $VSCODE_GIT_IPC_HANDLE || -n $VSCODE_NONCE ]]; then
+    ## if in VSCode, unset SSH_AUTH_SOCK to avoid endless 1Password prompt for ssh-agent
+    ## dev container seems to still set it, so we control from ssh wrapper
+    export SSH_AUTH_SOCK=""
+    exit_error
+  fi
 fi
+
+# if not in VSCode (eg Terminal), set ssh-agent
+export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
 
 # absolute path so we don't get into endless loop
 /Applications/1Password.app/Contents/MacOS/op-ssh-sign "$@"
