more subcommand handling

diff --git a/bin/git b/bin/git
--- a/bin/git
+++ b/bin/git
@@ -1,9 +1,26 @@
 #!/usr/bin/env bash
+set -eo pipefail
+
+exit_error() {
+    echo "ERROR: detected running in vscode. Aborting."
+    exit 1
+}
 
 if [[ -n $VSCODE_INJECTION && $VSCODE_INJECTION == "1" ]]; then
   ## if in VSCode, unset SSH_AUTH_SOCK to avoid endless 1Password prompt for ssh-agent
   ## dev container seems to still set it, so we control from ssh wrapper
   export SSH_AUTH_SOCK=""
+  if echo "$@" | grep -q -E '(amend|commit|merge|reb|rebase|revert)'; then
+    exit_error
+  fi
+  if echo "$@" | grep -q -E '(fetch|pull|push)'; then
+    if /usr/bin/git remote -v | grep -q '@'; then
+      exit_error
+    fi
+  fi
+  if echo "$@" | grep -q 'clone .*@'; then
+    exit_error
+  fi
 else
   # if not in VSCode, set ssh-agent
   export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
diff --git a/bin/op-ssh-sign b/bin/op-ssh-sign
--- a/bin/op-ssh-sign
+++ b/bin/op-ssh-sign
@@ -1,11 +1,16 @@
 #!/usr/bin/env bash
+set -eo pipefail
+
+exit_error() {
+    echo "ERROR: detected running in vscode. Aborting."
+    exit 1
+}
 
 if [[ -n $VSCODE_INJECTION && $VSCODE_INJECTION == "1" ]]; then
   ## if in VSCode, unset SSH_AUTH_SOCK to avoid endless 1Password prompt for ssh-agent
   ## dev container seems to still set it, so we control from ssh wrapper
   export SSH_AUTH_SOCK=""
-  echo "ERROR: detected running in vscode. Aborting."
-  exit 1
+  exit_error
 else
   # if not in VSCode, set ssh-agent
   export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
